#ifndef MESH_HANDLES_H
#define MESH_HANDLES_H

#define SENSOR_HANDLE(ID) (0x0100 + ID)
#define MESH_CONTROL_HANDLE (0x0201)
#define TEST_LED_HANDLE (0xfe01)
#define DEBUG_REGISTER_HANDLE (0x1234)

#endif // MESH_HANDLES_H
